### ISSUE TITLE
Change Login Server Port Number

### ISSUE THREAD

**Issue by jul-fls** [Jaggernaut555/midi-mixer-spotify#2]
I've had a problem with the login server not wanting to run and instead deactivating the plugin so i've thought that the tcp port of the web server may be the culprit.
So i've changed port 3000 everywhere (spotify app redirect uri, and everywhere in the code) to 45212 and no it works.
So i would suggest to change the port to one that is unlikely to be already used (pretty much everything between 20000 to 65534) so that nobody would have this problem again.
Otherwise, great plugin, great work !

**Comment by Jaggernaut555** [comment]
Yeah I just used the basic express port 3000 but it should be a really simple change to make it something less likely to conflict. Will probably be able to update this today when I have time.

**Comment by jul-fls** [comment]
Okay, no problem, take your time, it is not urgent as mine is working now.
Best Regards

**Comment by Jaggernaut555** [comment]
Took like a few minutes to update and test. Hopefully the new port doesn't end up conflicting for anyone.

Updated in version [v1.1.2](https://github.com/Jaggernaut555/midi-mixer-spotify/releases/tag/v1.1.2).
